steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean","install","-DskipTests"]    
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcloud", "--build-arg=JAR_FILE=Covid19_Infected_Cases-0.0.1-SNAPSHOT.jar", "."]
  - name: 'gcr.io/$PROJECT_ID/gcloud'
    args: ['info']
  - name: 'gcr.io/$PROJECT_ID/gcloud'
    args: ['source', 'repos', 'clone', 'default']    
images: ["gcr.io/$PROJECT_ID/gcloud"]
