steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean","install",-DskipTests]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/1/cb-hackathon", "--build-arg=JAR_FILE=Covid19_Infected_Cases-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/1/cb-hackathon"]
